---
title: "10-335 Final Project, Spring 2019: AI Horoscopes"
author: "Jenn Choi, Julie Kim, Sophia Yoo"
date: "Due Thursday April 25, 2019"
output: 
  html_document:
    toc:  true
    toc_float:  true
    code_folding:  show
---

```{r}
library(dplyr)
```

Horoscope Template - Text
```{r}
# Horoscope Template - Text
horoscopes = read.csv("horoscopes.csv")
```

```{r}
# `cal` dataframe for days of each month
cal = matrix(nrow = 31, ncol = 12)
cal = as.data.frame(cal)
colnames(cal) = month.name
cal[,c("January", "March", "May", "July", "August", "October", "December")] = 1:31
cal[,c("April", "June", "September", "November")] = c(1:30, NA)
cal[,"February"] = c(1:29, NA, NA)

# `bday.to.sign` function to take birthday and return a sign
bday.to.sign = function (day, month) {
  sign = "Capricorn"
  if (month == "January" & day > 20) {sign = "Aquarius"}
  if (month == "February" & day < 20) {sign = "Aquarius"}
  if (month == "February" & day > 19) {sign = "Pisces"}
  if (month == "March" & day < 21) {sign = "Pisces"}
  if (month == "March" & day > 20) {sign = "Aries"}
  if (month == "April" & day < 21) {sign = "Aries"}
  if (month == "April" & day > 20) {sign = "Taurus"}
  if (month == "May" & day < 22) {sign = "Taurus"}
  if (month == "May" & day > 21) {sign = "Gemini"}
  if (month == "June" & day < 22) {sign = "Gemini"}
  if (month == "June" & day > 21) {sign = "Cancer"}
  if (month == "July" & day < 23) {sign = "Cancer"}
  if (month == "July" & day > 22) {sign = "Leo"}
  if (month == "August" & day < 23) {sign = "Leo"}
  if (month == "August" & day > 22) {sign = "Virgo"}
  if (month == "September" & day < 24) {sign = "Virgo"}
  if (month == "September" & day > 23) {sign = "Libra"}
  if (month == "October" & day < 24) {sign = "Libra"}
  if (month == "October" & day > 20) {sign = "Scorpio"}
  if (month == "November" & day < 23) {sign = "Scorpio"}
  if (month == "November" & day > 22) {sign = "Sagittarius"}
  if (month == "December" & day < 22) {sign = "Sagittarius"}
  return(sign)
}

# `generate` function to choose a random horoscope given a sign
generate = function (data, sign, weekday) {
  horoscopes = filter(data, sign == sign) %>% 
    filter(day_of_week == weekday)
  i = sample(1:nrow(horoscopes), 1)
  return(list(as.character(horoscopes$horoscope[i]),
              as.character(horoscopes$img_path[i])))
}

# `recombine` function to split a horoscope by periods and paste with line breaks and images in between
recombine = function (list) {
  
  elements = unlist(strsplit(h[[1]], "(?<![^!?.])\\s+", perl = TRUE))
  
  paths = vector(length = 3)
  for (i in 1:3) {paths[i] = paste(h[[2]], ".", as.character(i), ".png", sep = "")}
  
  if (length(elements) == 1) {elements = c(elements, "", "", "")}
  if (length(elements) == 2) {elements = c(elements, "", "")}
  if (length(elements) == 3) {elements = c(elements, "")}
  
  group = round(length(elements)/4)
  
  texts = vector(length = 4)
  if (length(elements) == 4) {texts = elements} else {
    for (i in 1:3) {texts[i] = paste(elements[seq(1,length(elements),group)[i]:i+group-1], collapse = "")}
  }
  
  texts[4] = ifelse(length(elements) > group*3, paste(tail(elements, length(elements) - group*3), collapse = " "), "")
  
  return(list(texts, paths))
  
}
```

```{r}
# `compile` function to put images together
h = generate(horoscopes, "Leo", "Monday")
recombine(h)
```
